# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f3547fa755a252e0522686e18a44195798b9b042ae68ad27072ec082e174f082b48c859367ca7f17884c7f4551a5958a2fdf5cd77833b52cab04f2985d495db

test:
  secret_key_base: 758dc9eda3cb335482e2a9377d1d8cea6fc872f6762e8c253418c85aacd03d3e9c16f2bf6e60724b13613365970dffd728f9263cf7dfb3e5865c0348cff4bb70

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
